sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-23.0.2
    - android-23

script: cd Clover && ./gradlew build --console plain -x lint
